### ISSUE TITLE
Lesson plan document does not update when you edit or copy a SOLE

### ISSUE THREAD

**Issue by jsduffy** [startsole/StartSOLE-web-app#224] opened 2019-02-19 20:18 UTC
The iOS client appropriately updates PDFs when you edit the time/date for a lesson plan, but the webapp does not do this.

**Comment by jsduffy** [comment] 2019-02-25 16:14
Follow up requested with Stacey.Alinkoff@dta.k12.de.us

**Comment by drewrwilson** [comment] 2019-02-25 19:53
@FransGH or @SteffenJ would be better for this

**Comment by drewrwilson** [comment] 2019-03-12 15:14
update: we still can’t replicate it locally, but we did replicate it on production. our suspicion is that it’s a timing issue maybe or maybe caching. The one in the email is fine but the one on the web isn’t. Good news: we can replicate it on production. Bad news: no good leads. @SteffenJ and I are on the case!

**Comment by drewrwilson** [comment] 2019-03-12 15:45
another update: we think it has to do with the `clear` function in the backend. it appears that the PDF is being regenerated but the old one is not being cleared. and/or the database isn't updating with a link to the new one. still exploring. Just putting notes here because we likely won't finish today

**Comment by drewrwilson** [comment] 2019-03-12 15:53
we're thinking the next step is to write some console logs in the clear function on lines 93-108 so see what happens when we clear it

**Comment by drewrwilson** [comment] 2019-03-14 15:40
update from today. spent about 3.5h investigating. we found that it has something to do with the `isAdmin` in `Event.js` lines 136-139 ish. We reassign the user to the session and this user doesn't have a pub. 

```
            if (isAdmin && object.createdBy) {
                userPub = (className == "UserPub") ? object : object.createdBy;
                session.impersonate = userPub;
                session.user = userPub.priv;
            }
```

Question: is it possible that the user who reported this is an admin? We don't think so, but need to investigate this. 

Something strange in this block. Need to come back to this. Might be able to pair again tomorrow.

**Comment by drewrwilson** [comment] 2019-03-15 16:09
So where we landed is that it happens when someone is an admin but we can't reproduce it when a user is not an admin. We're doing two things:

 * looking into this user in specific to see if we can see what happened
 * we're writing fix script to fix any of these mistakes from the past (and also to see how many times it happened in the past)

the script is running right now, so while it runs we're looking into this specific user

**Comment by drewrwilson** [comment] 2019-03-15 16:12
We found that there are 492 documents that do not have corresponding Soles. That means we have documents generated where the parent Sole was deleted or the ID changed or something

**Comment by drewrwilson** [comment] 2019-03-15 16:29
Ok, we went too deep with this new issue and so I filed a new ticket for that in the backend: https://github.com/startsole/StartSOLE-backend/issues/78

Refocusing on the problem described in this issue.

**Comment by drewrwilson** [comment] 2019-03-15 17:35
Here are some things that we found out today:

 * plannedDuration is a special case because you can update it in the app at the beginning of facilitation
 * we need to recreate documents when default DPVs have been added to the sole
 * we need to fix the special case for admins. something related to the event controller

for this user we couldn't find a document that is outdated, at least according to the timestamps

for next time: look into whether this user has two accounts

**Comment by drewrwilson** [comment] 2019-03-15 17:37
@jsduffy: steffen would like to know if we can have more information about this. could we see the text of the email from the user if there is one? we looked in the support inbox and didn't see one. or perhaps we could talk to her? also are there other users who reported this?

**Comment by jsduffy** [comment] 2019-03-15 17:43
Hi Jeff!

Thank you for the email and great presentation yesterday. It was great to meet you, finally! I've been at DTA the past 2 years,  have been in Education for 17. I really love the SOLE program and look forward to using this with my classes. I wanted to write to thank you, but also to remind you about the inability to change the time on the lesson plan,  despite updating it! Let me know what you find out!

Thanks again and enjoy your weekend, 
Stacey

**Comment by jsduffy** [comment] 2019-03-15 17:43
@drewrwilson this may have been reported by other users as well, this is the email that generated the flag.  She's definitely not an admin

**Closed** 2019-03-21 19:08 UTC
Labels: Backlog, bug, followup-requested
